name: lakes
channels:
  - conda-forge
  - menpo
  - pytorch
  - anaconda
dependencies:
  - python=3.8
  - geopandas
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - opencv
  - pandas
  - rasterio
  - scipy
  - shapely
  - tensorboard
  - tensorboardx
  - tqdm
  - pip
  - pip:
    - torch
    - torchvision
